CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE TABLE IF NOT EXISTS services (id TEXT PRIMARY KEY DEFAULT uuid_generate_v4()::text, name TEXT NOT NULL, name_et TEXT, description TEXT NOT NULL DEFAULT '', description_et TEXT, price NUMERIC NOT NULL DEFAULT 0, duration_minutes INTEGER NOT NULL DEFAULT 30, active BOOLEAN NOT NULL DEFAULT true, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS bookings (id TEXT PRIMARY KEY DEFAULT uuid_generate_v4()::text, service_id TEXT NOT NULL, service_name TEXT, customer_name TEXT NOT NULL, customer_email TEXT NOT NULL, customer_phone TEXT, booking_date DATE NOT NULL, start_time TEXT NOT NULL, end_time TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'confirmed', notes TEXT, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS agent_settings (id TEXT PRIMARY KEY DEFAULT 'agent-main', system_prompt TEXT NOT NULL DEFAULT '', mode TEXT NOT NULL DEFAULT 'full_booking', business_name TEXT NOT NULL DEFAULT 'SmilePro Dental', business_hours TEXT NOT NULL DEFAULT 'Mon-Fri 9:00-18:00', business_address TEXT, business_phone TEXT, business_email TEXT, faq JSONB NOT NULL DEFAULT '[]', updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS chat_history (id TEXT PRIMARY KEY DEFAULT uuid_generate_v4()::text, session_id TEXT NOT NULL, role TEXT NOT NULL, content TEXT NOT NULL DEFAULT '', tool_calls JSONB, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS languages (code TEXT PRIMARY KEY, label TEXT NOT NULL, native_label TEXT NOT NULL, enabled BOOLEAN NOT NULL DEFAULT true);
CREATE TABLE IF NOT EXISTS profiles (id TEXT PRIMARY KEY, email TEXT NOT NULL, role TEXT NOT NULL DEFAULT 'admin', display_name TEXT, created_at TIMESTAMPTZ DEFAULT NOW());
ALTER TABLE services ENABLE ROW LEVEL SECURITY;
ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE chat_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE languages ENABLE ROW LEVEL SECURITY;
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "read_services" ON services FOR SELECT USING (true);
CREATE POLICY "write_services" ON services FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "read_settings" ON agent_settings FOR SELECT USING (true);
CREATE POLICY "write_settings" ON agent_settings FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "insert_bookings" ON bookings FOR INSERT WITH CHECK (true);
CREATE POLICY "read_bookings" ON bookings FOR SELECT USING (true);
CREATE POLICY "write_bookings" ON bookings FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "insert_chat" ON chat_history FOR INSERT WITH CHECK (true);
CREATE POLICY "read_chat" ON chat_history FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "read_languages" ON languages FOR SELECT USING (true);
CREATE POLICY "write_languages" ON languages FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "read_profiles" ON profiles FOR ALL USING (auth.role() = 'authenticated');
