INSERT INTO services (id, name, name_et, description, description_et, price, duration_minutes, active) VALUES
('svc-1', 'Dental Check-up', 'Hambakontroll', 'Comprehensive oral examination with X-rays', 'Põhjalik suuõõne läbivaatus koos röntgeniga', 75, 30, true),
('svc-2', 'Teeth Whitening', 'Hammaste valgendamine', 'Professional whitening session for a brighter smile', 'Professionaalne valgendamisseanss heledama naeratuse jaoks', 250, 60, true),
('svc-3', 'Dental Cleaning', 'Hammaste puhastus', 'Thorough cleaning and polishing by our hygienist', 'Põhjalik puhastus ja poleerimine meie hügienisti poolt', 120, 45, true),
('svc-4', 'Root Canal Treatment', 'Juureravi', 'Expert root canal procedure with modern equipment', 'Ekspert juureravi kaasaegse varustusega', 450, 90, true),
('svc-5', 'Dental Implant Consultation', 'Implantaadi konsultatsioon', 'Personalized implant planning session', 'Personaalne implantaadi planeerimise seanss', 100, 45, true),
('svc-6', 'Orthodontic Consultation', 'Ortodontia konsultatsioon', 'Assessment for braces or clear aligners', 'Hindamine breketite või läbipaistvate joondajate jaoks', 90, 30, true);
INSERT INTO agent_settings (id, system_prompt, mode, business_name, business_hours, business_address, business_phone, business_email, faq) VALUES ('agent-main', 'You are a friendly and professional dental receptionist for SmilePro Dental. Your name is Dr. Smile Assistant. Your responsibilities: Answer questions about services, prices, and business hours. Check appointment availability when customers want to book. Help customers book appointments by collecting their details. Be warm, professional, and concise. If asked about medical advice, politely redirect to booking a consultation. Business hours: Monday-Friday 9:00-18:00, Saturday 10:00-14:00, Sunday closed. Address: Pärnu mnt 25, Tallinn, Estonia. Always confirm the appointment details with the customer before making the booking.', 'full_booking', 'SmilePro Dental', 'Mon-Fri 9:00-18:00, Sat 10:00-14:00, Sun Closed', 'Pärnu mnt 25, Tallinn, Estonia', '+372 5555 1234', 'info@smileprodental.ee', '[{"question":"Do you accept insurance?","answer":"Yes, we accept all major dental insurance plans. Please bring your insurance card to your appointment."},{"question":"Is parking available?","answer":"Yes, free parking is available in front of the clinic."},{"question":"What payment methods do you accept?","answer":"We accept cash, credit/debit cards, and bank transfer."},{"question":"Can I cancel or reschedule?","answer":"Yes, you can cancel or reschedule up to 24 hours before your appointment at no charge."}]');
INSERT INTO languages (code, label, native_label, enabled) VALUES ('en', 'English', 'English', true), ('et', 'Estonian', 'Eesti', true);
